### ISSUE TITLE
one to many mapping of generators to trace CSVs

### ISSUE THREAD

**Issue by nick-gorman** [Open-ISP/isp-trace-parser#2]
The current approach for parsing the traces is to rename project trace files with generator names from the assumptions workbook. However, sometimes a single generator has several trace files it could map too. See example below:

Workbook:
![image](https://github.com/user-attachments/assets/f5e9b2a3-6091-4073-9cc0-b4ee8f3e13ec)

Trace files:
![image](https://github.com/user-attachments/assets/c1b874ae-8589-42bc-973e-8a91187863a4)

**Comment by nick-gorman** [comment]
For now, I'm just going to do a one-to-one mapping using the first file name, but to make this work we'll have to ignore trace files that don't have a corresponding workbook name.

**Comment by nick-gorman** [comment]
Another issue along these lines. Sometimes it appears that many generators within the workbook would map to the to the same trace file. This would cause an issue with our current method because we are renaming file with workbook names, but this would mean there are two renaming options.

**Comment by dylanjmcconnell** [comment]
There perhaps a broader question here relating about "generators" and "units".  The three Dundonnell traces map to the three different DUID's that make up the larger wind farm (loosely spread across three close be different locations). 

We will possibly come across this "generator" vs "unit" issue when it comes to some of the thermal plants as well - e.g. the minimum operating limits are at a dispatch unit level. 

I don't have a good solution to this for now - but just flagging could be related to broader design question.
